# Learning Dataset

### Test

In [2]:
from nba_api.stats.static import teams

nba_teams = teams.get_teams()
print(f"Number of teams: {len(nba_teams)}")
print(nba_teams[:5])

Number of teams: 30
[{'id': 1610612737, 'full_name': 'Atlanta Hawks', 'abbreviation': 'ATL', 'nickname': 'Hawks', 'city': 'Atlanta', 'state': 'Georgia', 'year_founded': 1949}, {'id': 1610612738, 'full_name': 'Boston Celtics', 'abbreviation': 'BOS', 'nickname': 'Celtics', 'city': 'Boston', 'state': 'Massachusetts', 'year_founded': 1946}, {'id': 1610612739, 'full_name': 'Cleveland Cavaliers', 'abbreviation': 'CLE', 'nickname': 'Cavaliers', 'city': 'Cleveland', 'state': 'Ohio', 'year_founded': 1970}, {'id': 1610612740, 'full_name': 'New Orleans Pelicans', 'abbreviation': 'NOP', 'nickname': 'Pelicans', 'city': 'New Orleans', 'state': 'Louisiana', 'year_founded': 2002}, {'id': 1610612741, 'full_name': 'Chicago Bulls', 'abbreviation': 'CHI', 'nickname': 'Bulls', 'city': 'Chicago', 'state': 'Illinois', 'year_founded': 1966}]

### Pull Team Stats

In [3]:
from nba_api.stats.endpoints import leaguedashteamstats

team_stats = leaguedashteamstats.LeagueDashTeamStats(season='2025-26').get_data_frames()[0]
team_stats.head()

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,82,46,36,0.561,3951.0,3575,7541,0.474,...,18,1,10,5,18,17,14,26,6,12
1,1610612738,Boston Celtics,82,56,26,0.683,3946.0,3456,7398,0.467,...,3,27,1,28,11,3,9,27,19,4
2,1610612751,Brooklyn Nets,82,20,62,0.244,3951.0,3071,6933,0.443,...,30,26,29,22,23,23,26,21,30,28
3,1610612766,Charlotte Hornets,82,44,38,0.537,3951.0,3357,7292,0.460,...,5,15,25,29,21,9,10,18,13,8
4,1610612741,Chicago Bulls,82,31,51,0.378,3951.0,3476,7417,0.469,...,9,7,23,23,11,26,8,24,12,22

### Explore Data

In [4]:
team_stats.columns
team_stats.describe()

,TEAM_ID,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
count,3.000000e+01,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,1.610613e+09,82.0,41.000000,41.000000,0.499967,3956.663556,3440.900000,7305.333333,0.471067,1090.566667,...,15.500000,15.466667,15.400000,15.400000,15.466667,15.433333,15.433333,15.400000,15.500000,15.500000
std,8.803408e+00,0.0,13.843958,13.843958,0.168850,11.276249,107.166435,180.602886,0.013193,128.932670,...,8.803408,8.756213,8.775357,8.853599,8.818997,8.799229,8.763889,8.810652,8.803408,8.803408
min,1.610613e+09,82.0,17.000000,18.000000,0.207000,3940.971667,3071.000000,6857.000000,0.443000,843.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.610613e+09,82.0,27.250000,30.000000,0.332250,3951.000000,3362.250000,7265.000000,0.462250,980.250000,...,8.250000,8.250000,8.250000,8.250000,8.250000,8.250000,8.250000,8.250000,8.250000,8.250000
50%,1.610613e+09,82.0,44.500000,37.500000,0.543000,3951.000000,3451.500000,7351.000000,0.467500,1119.500000,...,15.500000,15.500000,15.000000,15.000000,15.500000,15.000000,15.500000,15.500000,15.500000,15.500000
75%,1.610613e+09,82.0,52.000000,54.750000,0.634000,3961.000000,3517.250000,7402.500000,0.481750,1172.000000,...,22.750000,22.750000,22.750000,22.750000,22.750000,22.750000,22.750000,22.500000,22.750000,22.750000
max,1.610613e+09,82.0,64.000000,65.000000,0.780000,3986.000000,3582.000000,7648.000000,0.502000,1343.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000

### Column Key

| Column  | Meaning               |
| ------- | --------------------- |
| GP      | Games Played          |
| W       | Wins                  |
| L       | Losses                |
| W_PCT   | Win Percentage        |
| MIN     | Minutes Played        |
| FGM     | Field Goals Made      |
| FGA     | Field Goals Attempted |
| FG_PCT  | Field Goal Percentage |
| FG3M    | 3-Pointers Made       |
| FG3A    | 3-Pointers Attempted  |
| FG3_PCT | 3-Point Percentage    |
| FTM     | Free Throws Made      |
| FTA     | Free Throws Attempted |
| FT_PCT  | Free Throw Percentage |
| OREB    | Offensive Rebounds    |
| DREB    | Defensive Rebounds    |
| REB     | Total Rebounds        |
| AST     | Assists               |
| TOV     | Turnovers             |
| STL     | Steals                |
| BLK     | Blocks                |
| PTS     | Points Scored         |

### Save Raw Data

In [6]:
team_stats.to_csv("../data/raw/team_stats_2025_26.csv", index=False)